# ./Dockerfile 
# FROM pytorch/pytorch:1.6.0-cuda10.1-cudnn7-devel
FROM pytorch/pytorch:2.2.0-cuda11.8-cudnn8-devel

# Set the working directory in the container
WORKDIR /projects

# Configure timezone
RUN ln -snf /usr/share/zoneinfo/Asia/Seoul /etc/localtime

# Update 
# RUN rm /etc/apt/sources.list.d/cuda.list
# RUN rm /etc/apt/sources.list.d/nvidia-ml.list
# RUN apt-key del 7fa2af80 && apt-key adv --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/3bf863cc.pub

RUN apt-get update

# Jupyter 
RUN apt-get -y install python3 python3-pip
RUN python3 -m pip install ipykernel
RUN pip install jupyter

# Install requirements file
COPY requirements.txt ./
RUN pip install -r requirements.txt

## Copy all src files
COPY . ./